# Use the official MySQL image as the base image
FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=user_management_db
ENV MYSQL_USER=user_management_user
ENV MYSQL_PASSWORD=user_management_pwd

# Expose the MySQL port
EXPOSE 3306
